Updated save_the_date.py
czue/django-wedding-website pull request #25
Opened 2019-10-27 13:12 UTC by dillwishlist

Added context definitions to get_save_the_date_context so the save the date web previews would render variables properly from settings.py

2019-10-27 16:04 UTC, czue requested changes
Thanks for the contribution! i had one small piece of feedback. If you aren't able to address it I can also make the change later this week.

2019-10-27 16:04 UTC, czue commented on guests/save_the_date.py
> +    template_html = render_to_string(SAVE_THE_DATE_TEMPLATE, context=context)
I don't think this line should be here.

2019-10-27 22:15 UTC, dillwishlist reviewed
Removed offending line.

2019-10-27 22:15 UTC, dillwishlist commented on guests/save_the_date.py
> +    template_html = render_to_string(SAVE_THE_DATE_TEMPLATE, context=context)
I removed the last line of the four.  How's that look?

2019-10-28 06:53 UTC, czue approved these changes
perfect, thanks

2019-10-28 06:53 UTC, merged

2019-10-28 06:53 UTC, czue commented
thanks for the contribution!